FROM devwithlando/php:7.4-fpm-3

# Choose the major node version
ENV NODE_VERSION=12

# Install node
RUN curl -sL "https://deb.nodesource.com/setup_${NODE_VERSION}.x" | bash - \
  && apt-get install -y nodejs

# Install gulp-cli
RUN npm install gulp-cli gulp -g

# Install bcmath extension
RUN docker-php-ext-enable bcmath
