name: Lint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: turing-rk1-ubuntu
    container:
      image: mobomo/drupalstand-ci:8.0-latest
    steps:
    - uses: actions/checkout@v4
    - name: Globally install gulp-cli
      run: npm install --global gulp-cli
    - name: Install dependencies
      run: |
        composer install --no-interaction --no-progress
        npm install --prefix webroot/themes/custom/onr
        npm install --prefix webroot/themes/custom/onr_amp
    - name: Install Linters and Sniffers
      run: |
        composer global require --dev drupal/coder php-parallel-lint/php-parallel-lint --no-interaction
        echo "COMPOSER_DIR=$(composer -n config --global home)" >> $GITHUB_ENV
    - name: PHP Lint
      run: |
        $COMPOSER_DIR/vendor/bin/parallel-lint -e php,module,inc,install,test,profile,theme ./webroot/modules/custom ./webroot/themes/custom
    - name: PHP CodeSniff (ignore warnings)
      run: |
        $COMPOSER_DIR/vendor/bin/phpcs -ns --standard=./.phpcs.xml.dist
    - name: Theme Lint
      run: |
        cd webroot/themes/custom/onr && npx gulp lintCi