name: SonarScan

on:
  push:
    branches:
      - master

jobs:
  sonarscan:
    runs-on: ubuntu-latest
    container:
      image: sonarsource/sonar-scanner-cli
    steps:
    - uses: actions/checkout@v3
    - name: Run SonarQube scan
      run: sonar-scanner -Dsonar.projectKey=LandoStand-Drupal