name: Unit Test

on:
  push:
    branches:
      - master

jobs:
  unit_test:
    runs-on: turing-rk1-ubuntu
    services:
      mariadb:
        image: mariadb:10.5.12
        env:
          MYSQL_DATABASE: drupal
          MYSQL_USER: drupal
          MYSQL_PASSWORD: drupal
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
    container:
      image: mobomo/drupalstand-ci:8.2-ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        composer install --no-interaction --no-progress
        npm install --prefix webroot/themes/custom/onr
        npm install --prefix webroot/themes/custom/onr_amp
    - name: Initialize Drupal + Verify Config can import
      run: |
        # Your commands to initialize Drupal and import configuration
    - name: Unit Test
      run: php ./vendor/bin/phpunit -c ./phpunit.xml